[workspace]
channels = ["conda-forge"]
name = "OpenPCDet"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[system-requirements]
cuda = "12"

[dependencies]
python = "3.12.*"
pytorch-gpu = ">=2.11.0,<3"
torchvision = ">=0.26.0,<0.27"
tensorboard = ">=2.20.0,<3"
tqdm = ">=4.68.2,<5"
numba = ">=0.65.1,<0.66"
easydict = ">=1.13,<2"
pyyaml = ">=6.0.3,<7"
scikit-image = ">=0.26.0,<0.27"
pyquaternion = ">=0.9.9,<0.10"
py-opencv = ">=4.13.0,<5"
cuda-toolkit = ">=12.9.2,<13"
matplotlib-base = ">=3.10.9,<4"
scikit-learn = ">=1.9.0,<2"
cachetools = ">=7.1.4,<8"
gxx_linux-64 = ">=11,<14"
pip = ">=26.1.2,<27"

[pypi-dependencies]
spconv-cu121 = ">=2.3.8, <3"

